"""initial schema

Revision ID: b33914ffc4e3
Revises: 
Create Date: 2026-08-15 20:00:16.169126
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b33914ffc4e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('connector_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('CONFIGURED', 'NOT_CONFIGURED', 'CONNECTED', 'ERROR', name='connectorstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('saas_platform', sa.String(length=128), nullable=False),
    sa.Column('ai_capability', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED_PENDING_REVIEW', 'ENABLED', 'DISABLED', 'REVIEWED', name='assetstatus'), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('accessible_resources', sa.JSON(), nullable=False),
    sa.Column('discovery_source', sa.String(length=255), nullable=True),
    sa.Column('monitoring_status', sa.Enum('NOT_MONITORED', 'MONITORING', 'PARTIAL', 'LIMITED', 'NOT_AVAILABLE', name='monitoringstatus'), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='reviewstatus'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=True),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', 'RUNNING', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assets_found', sa.Integer(), nullable=False),
    sa.Column('accesses_found', sa.Integer(), nullable=False),
    sa.Column('interactions_found', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_asset_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('principal_type', sa.Enum('USER', 'GROUP', name='principaltype'), nullable=False),
    sa.Column('principal_id', sa.String(length=255), nullable=True),
    sa.Column('principal_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('access_level', sa.String(length=128), nullable=True),
    sa.Column('license_sku', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['ai_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('connection_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_display_name', sa.String(length=255), nullable=True),
    sa.Column('principal_type', sa.Enum('USER', 'GROUP', name='principaltype'), nullable=True),
    sa.Column('saas_application', sa.String(length=128), nullable=True),
    sa.Column('ai_feature', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('model_available', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_info', sa.Text(), nullable=True),
    sa.Column('request_available', sa.Boolean(), nullable=False),
    sa.Column('response_info', sa.Text(), nullable=True),
    sa.Column('response_available', sa.Boolean(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('usage_available', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('visibility_note', sa.Text(), nullable=True),
    sa.Column('raw_event', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['ai_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_interactions')
    op.drop_table('ai_asset_access')
    op.drop_table('runs')
    op.drop_table('ai_assets')
    op.drop_table('connections')
    # ### end Alembic commands ###
